export const API_METHOD = {
  GET: "GET",
  POST: "POST",
  PUT: "PUT",
  DELETE: "DELETE",
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const SocialLinkPlatform = {
    GITHUB: "GITHUB",
    GITLAB: "GITLAB",   
    BITBUCKET: "BITBUCKET",
    LINKEDIN: "LINKEDIN",
    STACKOVERFLOW: "STACKOVERFLOW",
    LEETCODE: "LEETCODE",
    HACKERRANK: "HACKERRANK",
    CODECHEF: "CODECHEF",
    CODEFORCES: "CODEFORCES",
    PORTFOLIO: "PORTFOLIO",
    RESUME: "RESUME",
    TWITTER: "TWITTER",
    X: "X",
    INSTAGRAM: "INSTAGRAM",
    FACEBOOK: "FACEBOOK",
    OTHER: "OTHER"
} as const;